version: '3'

networks:
  docker_network:

services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    restart: always
    networks:
      - docker_network
    # volumes:
    #   - wp:/var/www/wordpress
    ports:
      - "443:443"

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb/
    restart: always
    networks:
      - docker_network
    # volumes:
    #   - dp:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    networks:
      - docker_network
    # volumes:
    #   - wp:/var/www/wordpress
    env_file:
      - .env

# volumes:
#   wp:
#     driver: local
#     driver_opts:
#       type: mone
#       o: bind
#       device: /home/svan-ass/data/wordpress
#   dp:
#     driver: local
#     driver_opts:
#       type: mone
#       o: bind
#       device: /home/svan-ass/data/mariadb